### ISSUE TITLE
please add a license

### ISSUE THREAD

**Issue by krageon** [nakano15/NExperienceMod#1]
If I want to contribute patches to this repository I'll need to fork and clone it, but as it stands it is ambiguous whether or not that's allowed. It would be nice if you could add a software license (whichever one you think is good). Perhaps the GPL?

https://www.gnu.org/licenses/quick-guide-gplv3.html

**Comment by nakano15** [comment]
Depending on the usage, I don't mind contribution. A thing I don't like is code theft though.
By the way, do notice that this is for the 1.3 version of the mod. For 1.4, the code is "nexperience1dot4".

And yeah, sorry about the weeks delay for the answer. I got distracted with other stuffs.

**Comment by krageon** [comment]
With respect, "anything I don't like is code theft" is the kind of attitude I'm going to just give a miss. I wish you good luck with your modding.
